Import Functions

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

Import the Data

In [ ]:
data = pd.read_csv(r'C:\Users\MIKE\Desktop\Python Projects\1. Weather Data.csv')

Run the Data

In [13]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

.head()

In [14]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

.shape

In [16]:
data.shape

(8784, 8)

.index

In [17]:
data.index

RangeIndex(start=0, stop=8784, step=1)

.columns

In [18]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='str')

.dtypes

In [19]:
data.dtypes

Date/Time               str
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather                 str
dtype: object

.unique

In [23]:
data['Weather'].unique()

<StringArray>
[                                    'Fog',
                    'Freezing Drizzle,Fog',
                           'Mostly Cloudy',
                                  'Cloudy',
                                    'Rain',
                            'Rain Showers',
                            'Mainly Clear',
                            'Snow Showers',
                                    'Snow',
                                   'Clear',
                       'Freezing Rain,Fog',
                           'Freezing Rain',
                        'Freezing Drizzle',
                               'Rain,Snow',
                           'Moderate Snow',
                   'Freezing Drizzle,Snow',
               'Freezing Rain,Snow Grains',
                       'Snow,Blowing Snow',
                            'Freezing Fog',
                                    'Haze',
                                'Rain,Fog',
                             'Drizzle,Fog',
                                 'Drizzle',
                   'Freezing Drizzle,Haze',
                      'Freezing Rain,Haze',
                               'Snow,Haze',
                                'Snow,Fog',
                        'Snow,Ice Pellets',
                               'Rain,Haze',
                      'Thunderstorms,Rain',
              'Thunderstorms,Rain Showers',
        'Thunderstorms,Heavy Rain Showers',
          'Thunderstorms,Rain Showers,Fog',
                           'Thunderstorms',
                  'Thunderstorms,Rain,Fog',
 'Thunderstorms,Moderate Rain Showers,Fog',
                        'Rain Showers,Fog',
               'Rain Showers,Snow Showers',
                            'Snow Pellets',
                           'Rain,Snow,Fog',
                       'Moderate Rain,Fog',
           'Freezing Rain,Ice Pellets,Fog',
                 'Drizzle,Ice Pellets,Fog',
                            'Drizzle,Snow',
                        'Rain,Ice Pellets',
                        'Drizzle,Snow,Fog',
                        'Rain,Snow Grains',
                   'Rain,Snow,Ice Pellets',
                        'Snow Showers,Fog',
              'Moderate Snow,Blowing Snow']
Length: 50, dtype: str

Ununique()

In [25]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

Count()

In [26]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

Count Value

In [30]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Rain,Snow,Ice Pellets                         4
Snow Showers,Fog                              4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Rain,Fog                        1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain Showers,Fog                              1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

Data info()

In [31]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   str
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   str
dtypes: float64(4), int64(2), str(2)
memory usage: 549.1 KB

Finding this ununique value of the "wind speed"

In [32]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [37]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [41]:
data['Wind Speed_km/h'].nunique()

34

In [47]:
data.Weather.value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Rain,Snow,Ice Pellets                         4
Snow Showers,Fog                              4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Rain,Fog                        1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain Showers,Fog                              1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

In [ ]:
data['Weather'].nunique()